export const LANDING_PAGE = "/"
export const SIGNUP_PAGE = "/signup"
export const LOGIN_PAGE = "/login"
export const DASHBOARD_PAGE = "/dashboard"
export const CREATE_PAGE="/dashboard/create"
export const PLAN_PAGE="/dashboard/plan"
export const PAYSTE_PAGE="/dashboard/payste"
export const EDIT_PAGE="/dashboard/edit"